### PR TITLE
Reduce alchemy request

### PR DESCRIPTION
**Pull request by Emmanueldmlr**
stake page does 100 requests each few seconds to alchemy (this is probably some loops / unnecessary refreshes)

if you refresh the page https://iq.braindao.org/dashboard/stake it does 300 requests to load data.

idle in the homepage it refreshes balances every few seconds doing multiple requests for IQ and Hiiq (increase time to refresh or refresh when the user actually opens the menu w balances)

## Linked issues

fixes https://github.com/EveripediaNetwork/issues/issues/900

### CODE REVIEW

**Comment by Emmanueldmlr** [comment]
Before (It increases every second):

image

After (stable): 

image

**Comment by kesar** [comment]
please add screenshots of the important one and filter by alchemy requests

biggest problem is 300 alchemy requests per page refresh, you are showing homepage and mixing alchemy and no alchemy request

**Review by kesar — APPROVED** [review]

**Comment by Emmanueldmlr** [comment]
https://user-images.githubusercontent.com/70170061/204810103-3481a401-030b-4434-a66c-97cfee2cb31b.mov

@kesar, notice that it doesn't refresh every second.

**Comment by kesar** [comment]
looking good thanks for the video!

**Pull request merged**
