### PR TITLE
Fixes braindao logo

### PR DESCRIPTION
**Pull request by Adebesin-Cell**
Fixes braindao logo

Changes:
Updated favicon.ico
Added logo to sidebar and navbar.

fixes https://github.com/EveripediaNetwork/issues/issues/865

### CODE REVIEW

**Review by Softdev1 — APPROVED** [review]
Nice implementation @Adebesin-Cell

**Review by Simplypheyie96 — COMMENTED** [review]
i'll try and work on some svg and see what we can do  about that situation

**Comment by Simplypheyie96** [comment]
here are the svgs @Adebesin-Cell 
https://www.figma.com/file/wosuJaHeV318k1ON82CZpo/%F0%9F%A7%A0-IQ.WIKI?node-id=11450%3A96407

**Review by Simplypheyie96 — APPROVED** [review]
Looks good now

**Pull request merged**
