### PR TITLE
updates formatContractResult

### PR DESCRIPTION
**Pull request by Emmanueldmlr**
There seems to be a rounding error in the frontend. There are some transactions that fail when the increase_amount method is called.

fixes https://github.com/EveripediaNetwork/issues/issues/858

### CODE REVIEW

**Review by kesar — APPROVED** [review]

**Review by kesar — COMMENTED** [review]
have u tested it ? I am wondering if that cast to number is gonna have an issue w bigNumbers

**Comment by Emmanueldmlr** [comment]
Yes, I have tested it. I'm sorry for the late response.

image

**Comment by Emmanueldmlr** [comment]
Yes, I have tested it. I'm sorry for the late response.

image

**Comment by Emmanueldmlr** [comment]
Yes, I have tested it. I'm sorry for the late response.

image

**Review by kesar — APPROVED** [review]

**Pull request merged**
