### PR TITLE
Iq dashboard UI

### PR DESCRIPTION
**Pull request by OleanjiKingCode**
# IQ Dashboard  UI, colors, text, arrangement 
- [x] Change font to Montserrat, with minimum font weight of 500

- [x] Improve color contrast across the pages, especially in dark mode for better contrast.(inspect all figma designs)
examples include, all gray 200 have been updated to gray 300
                                white alpha200 to white alpha 300, in dark mode, lowest font color in dark mode is whitle-alpha 700 etc

- [x] Improve consistency with spacing on top of each pages. check figma to make adjustments. They are all starting on different planes, so adjust each one

- [x] Inspect bridge, Lock and staking page for text color and font size adjustments.

- [x] Under staking page, bigger screens should display the whole table

- [x] Rearrange bar on Lock page and adjust naming of contents in bar

- [x] Rearrange bar on staking page too

- [x] Adjusting spacing on the bridge page for the box.

- [x] Fix broken image on the dashboard and adjust double minus on the IQ price which shouldn't be there since the number is green. (only red numbers carry negative sign)
- [x] The number in green should be in percentage (this is on the dashboard) and also the market cap, the green one has a minus which shouldn't be there if it's an increase

- [x] reiterate on the IQ voting page (under the old votes). The cards are not the correct size and the margins on the sides are too large. see figma for correct implementation: https://www.figma.com/file/wosuJaHeV318k1ON82CZpo/%F0%9F%A7%A0-EVERIPEDIA?node-id=4707%3A34782

- [x] Adjust spacing on the page too. between the description and page subtitle pages and update the description as it is on 

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/699, closes https://github.com/EveripediaNetwork/issues/issues/702

### CODE REVIEW

**Review by Simplypheyie96 — COMMENTED** [review]
WELL DONE.
- [x] Change all the normal font to medium. minimum weight should be 500
- [ ] change all gray 200 to gray 300 and white-alpha 200 to white-alpha 300 in dark mode(the color for strokes around the boxes).
- [ ] Although the headings and descriptions are consistent now, the spacing above is still too much. please inspect figma to give right spacing.
image

- [x] A lot of the texts on the pages are yet to be inspected for changes in font weight and colors. please inspect figma so the contrast can be improved. (it is a lot of work inspecting each element but it is necessary).
- [x] Make the whole table under staking visible on bigger screens (this was not done)
- [x] Change ux writing for Iq voting page empty state (check on figma to see text)
image
Every other thing looks great.

**Comment by Simplypheyie96** [comment]
new additions
-[ ] Adjusting space shouldn't affect the side content. it is now too narrow.
image
- [ ] reduce size of the token boxes 
image
- [ ] on the voting page, when you move between tabs line and content moves, it should try to keep same layout on inactive state to prevent the movement of all the content. adjust the pages to prevent movement of contents
- [ ] The learn on the sidebar should be linked to the correct site: https://learn.everipedia.org/iq/ and rename everipedia on the left sidebar to IQ.Wiki
image

**Review by Simplypheyie96 — COMMENTED** [review]
a lot of them have not been reviewed for contrast issues adjustment. like the bridge page, lock page, stats, please help check everything.
image
I can still see some text with font weight less than 500. the smallest weight should be font weight 500.(medium font) for readability

**Comment by kesar** [comment]
merging this since its already pretty big PR and has a lot of improvements. We can open a follow up issue with missing  / remaining improvements 👍🏻

**Pull request merged**
