### PR TITLE
Color fixes on Bridge Page

### PR DESCRIPTION
**Pull request by anubra266**
Closes EveripediaNetwork/issues#577

### CODE REVIEW

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
some icons are missing.

**Comment by anubra266** [comment]
> some icons are missing.

@Simplypheyie96 
- [ ] That's outside the scope of this Pr, please open a different issue
- [ ] I'm not sure what icons are missing on the bridge page.

**Comment by Simplypheyie96** [comment]
> > some icons are missing.
> 
> @Simplypheyie96
> 
> * [ ]  That's outside the scope of this Pr, please open a different issue
> * [ ]  I'm not sure what icons are missing on the bridge page.

sorry. i have lots of tabs opened. i wrote in d wrong pr

**Comment by Simplypheyie96** [comment]
image
please check on figma @anubra266

**Comment by anubra266** [comment]
> image please check on figma @anubra266

@Simplypheyie96 Wrong PR?

**Comment by Simplypheyie96** [comment]
> > image please check on figma @anubra266
> 
> @Simplypheyie96 Wrong PR? This PR is for colors fix on bridge page.

you named it color fixes. i didn't know it was just the bridge part

**Comment by Simplypheyie96** [comment]
can you put a before and after. i am not sure what was fixed @anubra266

**Review by Simplypheyie96 — APPROVED** [review]

**Review by Simplypheyie96 — APPROVED** [review]

**Pull request merged**
