### PR TITLE
Migrate IQ dashboard

### PR DESCRIPTION
**Pull request by OleanjiKingCode**
# Migrating IQ Dashboard to the sepolia testnet

_The IQ dashboard is being migrated to a more gas-efficient testnet for the development environment, sepolia network is new compared to the current goerli testnet and there is more availability of sepolia test tokens compared to goerli _

Changes to be made :

- [x] Swap all contract goerli addresses used in the dev envs to sepolia in config
- [x]  and on vercel
- [x] Get Balances in sepolia and change network should be directed to sepolia 
- [ ] Test the new changes 

## Linked issues
closes https://github.com/EveripediaNetwork/issues/issues/1273

### CODE REVIEW

**Review by Emmanueldmlr — APPROVED** [review]

**Comment by OleanjiKingCode** [comment]
It has been redeployed from the update to the env vars i made
it now pops up

**Comment by Emmanueldmlr** [comment]
LGTM

**Review by Softdev1 — APPROVED** [review]

**Comment by Softdev1** [comment]
What is the blocker on this issue @OleanjiKingCode

**Comment by OleanjiKingCode** [comment]
image
we need to verify the deployed contracts in sepolia network but its not supported by hardhat, ---> this is the blocker @Softdev1

**Pull request closed without merging**
