### PR TITLE
Fixes too many requests

### PR DESCRIPTION
**Pull request by Emmanueldmlr**
- [x] homepage/navbar
loading homepage makes 108 requests, many repeated several times. I think the navbar refreshes the component many times (for example my ENS avatar loads 9 times) or flags 2x

- [x] swap
and just navigating to swap which is a static page, it does 100 requests to blockchain/avatars and so on when it should prob. not request any extra call or 2 or 3 max. if we want to refresh gas/ens

- [x] locking
locking page performs 400 requests 

- [x] raffles
refreshing the raffle page and clicking on a raffle takes several seconds to load the page and makes a bunch of requests. It should be almost instant since JSON content is static.

fixes https://github.com/EveripediaNetwork/issues/issues/734

### CODE REVIEW

**Review by kesar — APPROVED** [review]
looking great 👍🏻

**Comment by Emmanueldmlr** [comment]
@kesar for the lock page, I had to remove the watch properties from the useContractRead...It's causing unnecessary re-fetching. Do you think there is a side effect for it?

**Comment by Emmanueldmlr** [comment]
I will check if there is any alternative or maybe we can keep it for reward and balance?

**Comment by Emmanueldmlr** [comment]
@kesar, I added the watch for the balance, total lock Iq, and the end date. and already fixed the merge conflicts.

**Comment by kesar** [comment]
awesome, lets merge

**Pull request merged**
