### PR TITLE
Feat/hiiq holders table

### PR DESCRIPTION
**Pull request by invisiblemask**
# Add HIIQ Holders Table

_This PR introduces the addition of HIIQ holders table to the dashboard_

- Table consists of the total count for HIIQ holders which is updated daily
- Lists of all the holders with their addresses, balance, and date staked which is also updated daily

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/3369
closes https://github.com/EveripediaNetwork/issues/issues/3423

### CODE REVIEW

**Comment by SidharthK2** [comment]
@Simplypheyie96 We don't have `date staked` data as of now, what do you think we should replace it with? or omit it entirely.

**Comment by Simplypheyie96** [comment]
> @Simplypheyie96 We don't have `date staked` data as of now, what do you think we should replace it with? or omit it entirely.

Oh.
It was in the wireframe given. Do we have data for date of the last stake?

**Comment by Simplypheyie96** [comment]
image
@invisiblemask Great. let's update the divider's color in both dark and light mode and also refresh button is not working still

**Comment by Dewalz** [comment]
when the HiIq holder tab is selected, the hover effect on the stake in side bar disappears 
Screenshot 2024-11-21 at 1 46 25 PM

**Comment by Dewalz** [comment]
the gray fill is missing in light mode 
Screenshot 2024-11-21 at 1 49 17 PM

**Review by Dewalz — APPROVED** [review]

**Review by Simplypheyie96 — COMMENTED** [review]
- Adjust font color in light mode: 
image
- We probably shouldn't have this page if there is no result to display
image
- Let's adjust the table on mobile breakpoint
image

- The wallet addresses are not routing to any link for details. If they will not be clickable(which they should be), then they should be turned to normal text color.
image

**Review by Simplypheyie96 — APPROVED** [review]
I think we are good now. Hopefully the other things would be updated.

**Review by SidharthK2 — APPROVED** [review]

**Pull request merged**
