### PR TITLE
Raffles UI design

### PR DESCRIPTION
**Pull request by Emmanueldmlr**
# Implements Raffle Page

_PR description goes here_

## How should this be tested?

for now we wont have API, so create an structured json w all the needed info for all the different raffles that we will update each time we have a new raffle.

we do a raffle each 2 months so it does not makes sense to complicate stuff w db & api

## Notes or observations

_jot down something here_

## Linked issues

fixes https://github.com/EveripediaNetwork/issues/issues/685
fixes https://github.com/EveripediaNetwork/issues/issues/704

### CODE REVIEW

**Comment by Emmanueldmlr** [comment]
@kesar @Simplypheyie96, I think we should have a design for the raffle empty state.

**Comment by Emmanueldmlr** [comment]
@Simplypheyie96, I have implemented the changes you made to the raffle page. I need the design for the other breakpoint (sm and md). Also, don't forget the raffle page's empty state design.

**Comment by Emmanueldmlr** [comment]
@Simplypheyie96, you can test now...
Link: https://iq-dashboard-i4e5yzyxo-prediqt.vercel.app/dashboard

**Review by Simplypheyie96 — COMMENTED** [review]
Great Job!
But the numbers should be centered. check figma again
image
Then add just tabe title color in dark mode.

**Comment by Emmanueldmlr** [comment]
@Simplypheyie96, fixed now. Thanks

**Review by kesar — APPROVED** [review]

**Pull request merged**
