### PR TITLE
Bridge implementation

### PR DESCRIPTION
**Pull request by anubra266**
# Bridge implementation
Enables token bridging between EOS and ETH back and forth

Closes EveripediaNetwork/issues#621

### CODE REVIEW

**Comment by JustinCast** [comment]
image
image

@kesar @Simplypheyie96 what do you think about placing the $ estimate like this?

**Comment by Simplypheyie96** [comment]
How about breaking it when it reaches a max breaking point.

**Comment by kesar** [comment]
you could also build a helper to simplify numbers based on https://github.com/cfj/short-number/blob/master/index.js

0.XX
1.XX
1X
1XX
1XXX
and more than 10k 11k, 12k, 100k, etc. 

I dont think its gonna change to someone swapping 10k$ worth IQ to show 10123.33 or ≈10K$

**Comment by JustinCast** [comment]
> you could also build a helper to simplify numbers based on https://github.com/cfj/short-number/blob/master/index.js
> 
> 0.XX 1.XX 1X 1XX 1XXX and more than 10k 11k, 12k, 100k, etc.
> 
> I dont think its gonna change to someone swapping 10k$ worth IQ to show $10123.33 or ≈$10K
> 
> (that helper could be used everywhere in the dashboard)

good idea

**Comment by JustinCast** [comment]
> 

That could work

**Comment by JustinCast** [comment]
> How about breaking it when it reaches a max breaking point.

That could work

**Comment by JustinCast** [comment]
@kesar I'm aware about a couple of "any" warnings in the code. Those ones are related with the response of the eos tx. I've been searching the right type in the library

**Comment by JustinCast** [comment]
@kesar all warnings related to the bridge section were successfully fixed!.
Should we merge?

**Pull request merged**
