### PR TITLE
staking page

### PR DESCRIPTION
**Pull request by anubra266**
Staking page

### CODE REVIEW

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
this doesn't look right
image

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
the text sizes for this section is not yet correct
image

**Review by Emmanueldmlr — APPROVED** [review]

**Comment by kesar** [comment]
@anubra266 @Emmanueldmlr design is very different than the one in figma. Please make sure it looks similar since that's the main point of doing the first round of UI without implementing APIs.

@Simplypheyie96 pointed out a design issue and you just merged it. There are even more, just in a simple review:

- table has not sorting
- missing icons in table for logos
- missing icon for external link
- font seems to be bold in design in table
- in non dark mode bg of values is wrong (grey)
- font sizes are very small

image

image

**Comment by anubra266** [comment]
> @anubra266 @Emmanueldmlr design is very different than the one in figma. Please make sure it looks similar since that's the main point of doing the first round of UI without implementing APIs.
> 
> 
> 
> @Simplypheyie96 pointed out a design issue and you just merged it. There are even more, just in a simple review:
> 
> 
> 
> - table has not sorting
> 
> - missing icons in table for logos
> 
> - missing icon for external link
> 
> - font seems to be bold in design in table
> 
> - in non dark mode bg of values is wrong (grey)
> 
> - font sizes are very small
> 
> 
> 
> image
> 
> 
> 
> image
> 
> 

@kesar ill check out the font irregularities, I left out icons because those will be determined by the data, from the API. But I'll go ahead and add placeholders

**Comment by kesar** [comment]
> > @anubra266 @Emmanueldmlr design is very different than the one in figma. Please make sure it looks similar since that's the main point of doing the first round of UI without implementing APIs.
> > @Simplypheyie96 pointed out a design issue and you just merged it. There are even more, just in a simple review:
> > 
> > * table has not sorting
> > * missing icons in table for logos
> > * missing icon for external link
> > * font seems to be bold in design in table
> > * in non dark mode bg of values is wrong (grey)
> > * font sizes are very small
> > 
> > image
> > image
> 
> @kesar ill check out the font irregularities, I left out icons because those will be determined by the data, from the API. But I'll go ahead and add placeholders

those are gonna be most likely our real rows and icons so feel free to go ahead and add them. We might just get API for TVL or APR since this is gonna change very little. Its mostly informative 👍🏻

**Comment by Simplypheyie96** [comment]
@kesar There are other things asides these that I have listed to them on discord. I was planning on opening an issue if they weren't solved. But they said they will work on it

**Pull request merged**
