### PR TITLE
Upgrading Wagmi

### PR DESCRIPTION
**Pull request by OleanjiKingCode**
# Upgrading Wagmi Version in IQ UI

## Linked Issues
closes https://github.com/EveripediaNetwork/issues/issues/1501

### CODE REVIEW

**Review by Emmanueldmlr — APPROVED** [review]

**Comment by Emmanueldmlr** [comment]
@Softdev1 , we need to fully test the changes before we merge.

**Comment by Softdev1** [comment]
Sure, we can test it now to avoid the issue being raised later. Thanks, @Emmanueldmlr

**Review by Softdev1 — CHANGES_REQUESTED** [review]
I have conducted a test on what was done, Here are the feedback 

- Users Can't use wallet connect to connect, I mean it is not working at all 
- Allowance is not taking effect on all 
- Lock button is not working for both Increase stake IQ and Stake More IQ

**Review by Softdev1 — CHANGES_REQUESTED** [review]
Based on my testing, On the stake more tab, you can't lock at all and it is displaying a toss of  Allowance too small  which is not supposed to work that way 
SCR-20230720-pucy

**Comment by OleanjiKingCode** [comment]
@Softdev1 pls test again that issue has been fixed use this link
[preview](https://iq-dashboard-my2yfee91-prediqt.vercel.app/)

**Pull request merged**
