### PR TITLE
Mobile View Minor changes on IQ Dashboard

### PR DESCRIPTION
**Pull request by OleanjiKingCode**
# Iq dashboard responsiveness

- [x] Fix the md and mobile breakpoint for the voting page on the iq dashboard. (view correct design on figma). 
Image is not properly centered on the md bp and the mobile breakpoint and there seems to be something wrong with old votes tabs. it no longer brings out the cards from snapshot and even the empty page is not showing correctly.

- [x] Change page description for IQ voting page. Correct description on figma

- [x] Adjust the small info box on the lock and staking page in mobile breakpoint

- [x] Adjust stats page on mobile breakpoint. A part of the page has been cut off and it needs a little bit of spacing before the nav bar.

- [x] update page description for IQ raffles page

- [x] Fix extra spaces on both sides of the nav bar. Check figma for correct spacing.>

- [x] fix merged frames on dashboard for the medium breakpoint

closes https://github.com/EveripediaNetwork/issues/issues/756

### CODE REVIEW

**Comment by kesar** [comment]
" I don't know how this will be fixed, but it takes too long for the voting page to respond upon clicking it. and the page doesn't open until you click outside" <- perhaps @Emmanueldmlr can you help w that?

**Comment by OleanjiKingCode** [comment]
> " I don't know how this will be fixed, but it takes too long for the voting page to respond upon clicking it. and the page doesn't open until you click outside" <- perhaps @Emmanueldmlr can you help w that?

okay @kesar

**Comment by Emmanueldmlr** [comment]
@OleanjiKingCode, I took the task about voting performance out so it doesn't block this PR.

**Review by Emmanueldmlr — APPROVED** [review]

**Comment by kesar** [comment]
awesome 👍🏻

**Pull request merged**
