### PR TITLE
Adds cvxFXS  token on Frax

### PR DESCRIPTION
**Pull request by SidharthK2**
# Adds cvxFXS  token on Frax

This PR works on adding cvxFXS token on frax

image

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/2685

### CODE REVIEW

**Review by Adebesin-Cell — COMMENTED** [review]
Screenshot 2024-06-04 at 1 27 20 AM

Graph data is broken :))

**Comment by Aliiiu** [comment]
> Screenshot 2024-06-04 at 1 27 20 AM
> Graph data is broken :))

Not broken but the backend is not returning any data for dev

Dev
image

Prod
image

**Comment by kesar** [comment]
lets get this tested and merged, treasury is missing this amount of tokens

**Comment by SidharthK2** [comment]
> > Screenshot 2024-06-04 at 1 27 20 AM
> > Graph data is broken :))
> 
> Not broken but the backend is not returning any data for dev
> 
> Dev image
> 
> Prod image

image

Let's also check for others

**Comment by Softdev1** [comment]
> lets get this tested and merged, treasury is missing this amount of tokens

On it sir

**Comment by Aliiiu** [comment]
> > > Screenshot 2024-06-04 at 1 27 20 AM
> > > Graph data is broken :))
> > 
> > 
> > Not broken but the backend is not returning any data for dev
> > Dev image
> > Prod image
> 
> image image
> 
> Let's also check for others

Mostly caching, would change the name to see if it resolves it because it is showing well on local

**Comment by Aliiiu** [comment]
image

@SidharthK2

**Pull request merged**
