### PR TITLE
updates frax logo

### PR DESCRIPTION
**Pull request by Emmanueldmlr**
# Update the Frax logo on the Treasury page

_The Frax logo on the treasury page needs to be updated to the most recent logo and all these will happen on the treasury page as requested by the stakeholders. so kindly check this link to update all the logos related to frax ecosystem to the latest ones

result:
image

## Linked issues

fixes https://github.com/EveripediaNetwork/issues/issues/1206

### CODE REVIEW

**Comment by Emmanueldmlr** [comment]
image

**Review by Royal-lobster — APPROVED** [review]

**Comment by kesar** [comment]
make sure in treasury all frax related logos are fine as well

**Comment by Emmanueldmlr** [comment]
image

**Comment by Emmanueldmlr** [comment]
image

**Comment by Emmanueldmlr** [comment]
image

**Review by kesar — APPROVED** [review]

**Pull request merged**
