### PR TITLE
Voting fixes

### PR DESCRIPTION
**Pull request by anubra266**
FIxes https://github.com/EveripediaNetwork/issues/issues/590

### CODE REVIEW

**Comment by kesar** [comment]
Captura de Pantalla 2022-08-24 a las 9 19 19

I feel we can create a better UX design than this for empty states. Also please @anubra266 @Simplypheyie96 lets make sure we fix the margins of the pages to have the same everywhere. Compare Voting and Staking.

**Comment by Simplypheyie96** [comment]
> Captura de Pantalla 2022-08-24 a las 9 19 19
> 
> I feel we can create a better UX design than this for empty states. Also please @anubra266 @Simplypheyie96 lets make sure we fix the margins of the pages to have the same everywhere. Compare Voting and Staking. (not sure which one is the right one, up to you guys)

I will assign the empty state to gabriel.
for the margins issue, I plan on taking note of all and opening an issue for all of those little fixes.

**Comment by anubra266** [comment]
In that case @Simplypheyie96 @kesar Are there any further changes neccessary for this PR?

**Comment by Simplypheyie96** [comment]
> Visit Preview

Everything looks good. will create issues for other things that needs fixing

**Review by kesar — APPROVED** [review]

**Pull request merged**
