### PR TITLE
Treasury page

### PR DESCRIPTION
**Pull request by dever-oss**
Treasury page Closes EveripediaNetwork/issues#596

### CODE REVIEW

**Review by Emmanueldmlr — APPROVED** [review]

**Comment by kesar** [comment]
"UI implement it getting balances from etherscan or other api availabe that gives values for tokens" <- this is missing

**Comment by Emmanueldmlr** [comment]
@Softdev1 , I think you should always specify if the task is only the UI design implementation or if it includes API integration.

**Comment by kesar** [comment]
> @Softdev1 , I think you should always specify if the task is only the UI design implementation or if it includes API integration.

issue description clearly says get data from API :P but yeah, we can try to make it more obvious.

Its fine to do 2 different PRs, but PRs description cannot "CLOSE" the issue since its not complete. 👍🏻

**Comment by Softdev1** [comment]
Thanks for the observations actually @Emmanueldmlr

**Pull request closed without merging**
