### PR TITLE
revise currencies format

### PR DESCRIPTION
**Pull request by anubra266**
revise-dollar

### CODE REVIEW

**Comment by Simplypheyie96** [comment]
i need a preview link @anubra266

**Comment by kesar** [comment]
> i need a preview link @anubra266

image

there is always a preview view in the first comment of the pull request 👍🏻

**Comment by Simplypheyie96** [comment]
> > i need a preview link @anubra266
> 
> image
> 
> there is always a preview view in the first comment of the pull request 👍🏻

it wasn't showing before. thanks

**Comment by Simplypheyie96** [comment]
Also @anubra266 should i open a different one for everipedia? because we need to fix for everipedia too.

**Comment by anubra266** [comment]
> Also @anubra266 should i open a different one for everipedia? because we need to fix for everipedia too.

@Simplypheyie96 Already opened a PR there. Have you seen it?

**Comment by Simplypheyie96** [comment]
> > Also @anubra266 should i open a different one for everipedia? because we need to fix for everipedia too.
> 
> @Simplypheyie96 Already opened a PR there. Have you seen it?

seen!!!

**Review by Simplypheyie96 — APPROVED** [review]

**Review by Simplypheyie96 — APPROVED** [review]

**Pull request merged**
