### PR TITLE
IQ allowance staking issue

### PR DESCRIPTION
**Pull request by OleanjiKingCode**
# IQ Allowance staking issue

When staking now, a user needs to sign a transaction to allow the spending first before signing the actual stake transaction and due to the new feature of metamask, if the amount to be approved is reduced and the allowance amount is lesser than the original amount staked then the transaction fails.

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/1064

### CODE REVIEW

**Comment by kesar** [comment]
pls before pushing to prod lets make sure its tested properly. when we write code that its related to staking / moving money we need to be extra secure 👍🏻 

@Softdev1 make sure you test it before getting merge 🙏🏻

**Comment by OleanjiKingCode** [comment]
> pls before pushing to prod lets make sure its tested properly. when we write code that its related to staking / moving money we need to be extra secure 👍🏻
> 
> @Softdev1 make sure you test it before getting merge 🙏🏻

yes,

**Comment by Softdev1** [comment]
Okay , I will ensure that it gets tested sir @kesar

**Comment by Emmanueldmlr** [comment]
I think we can merge when you are done fixing the code climate issues @OleanjiKingCode .

**Review by Emmanueldmlr — APPROVED** [review]

**Comment by Emmanueldmlr** [comment]
Safe to merge now.

**Review by Softdev1 — APPROVED** [review]

**Pull request merged**
