### PR TITLE
Fix brainies logo

### PR DESCRIPTION
**Pull request by Emmanueldmlr**
- [x] The brainies logo is missing on the mobile and medium breakpoint.
- [x] I don't know how this will be fixed, but it takes too long for the voting page to respond upon clicking it. and the page doesn't open until you click outside.

fixes https://github.com/EveripediaNetwork/issues/issues/762

### CODE REVIEW

**Comment by Emmanueldmlr** [comment]
@OleanjiKingCode @kesar, kindly confirm that I used the right snapshot link. I got it from the main branch.

**Comment by Emmanueldmlr** [comment]
@Simplypheyie96, can we get a Brainies icon with a transparent background?.

**Comment by Emmanueldmlr** [comment]
> > @Simplypheyie96, can we get a Brainies icon with a transparent background?.
> 
> The ones on figma are without backgrounds

Thanks. Fixed now.

**Comment by Emmanueldmlr** [comment]
I think we are good to go🚀

**Review by Simplypheyie96 — APPROVED** [review]

**Review by OleanjiKingCode — APPROVED** [review]

**Pull request merged**
