### PR TITLE
Add Claim Warning

### PR DESCRIPTION
**Pull request by SidharthK2**
# Add Claim Warning

- Check if user has claimed reward before unlocking
image

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/2551

### CODE REVIEW

**Comment by kesar** [comment]
if srujan is full of reviews please assign somebody else. @Softdev1 ensure you test this as well 👍🏻

**Comment by Royal-lobster** [comment]
Oh i was awaiting reviews to this pr cuz its still draft

**Comment by kesar** [comment]
@Softdev1 plz reasign somebody else if needed. this has been for several weeks without merge. I think sid is working in the IQ Testnet thingy rn

**Comment by SidharthK2** [comment]
> @Softdev1 plz reasign somebody else if needed. this has been for several weeks without merge. I think sid is working in the IQ Testnet thingy rn

This would be merged today ser, just cleaning up some code and configs.

**Comment by Royal-lobster** [comment]
@SidharthK2 Its not showing my balance down in stake also throwing "Value cannot be greater than the available balance" when i enter value in it, is there any minimum value to stake ?

CleanShot 2024-05-15 at 18 15 36

**Comment by SidharthK2** [comment]
> @SidharthK2 Its not showing my balance down in stake also throwing "Value cannot be greater than the available balance" when i enter value in it, is there any minimum value to stake ?
> 
> CleanShot 2024-05-15 at 18 15 36

We use WIQ for staking on dev, the balance on staking component reflects your WIQ balance.

**Comment by Aliiiu** [comment]
image
image

Reducing the reward threshold to show the modal, I got this

**Review by Aliiiu — APPROVED** [review]

**Pull request merged**
