### PR TITLE
Fixes iq iteration

### PR DESCRIPTION
**Pull request by Emmanueldmlr**
# Fixes iq iteration

- [x] Remove the settings tab on the side nav. (check figma for new spacing.
- [x] Learn & IQ.Wiki links should be external and open in new tab (_blank)
- [x] adjust some broken cards on the IQ old votes page
image
- [x] fix hydratations errors
Captura de Pantalla 2022-09-30 a las 9 38 53

fixes https://github.com/EveripediaNetwork/issues/issues/766

### CODE REVIEW

**Review by kesar — APPROVED** [review]

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
Perhaps, you can bring learn and iq.wiki up a little bit more. and leave in some space below. 
on figma there is like 56px spacing
image

**Comment by Simplypheyie96** [comment]
it seems there is nothing we can do about this right? @Emmanueldmlr 
image

**Comment by Emmanueldmlr** [comment]
> it seems there is nothing we can do about this right? @Emmanueldmlr image

more like deleting them right?

**Comment by Emmanueldmlr** [comment]
> Perhaps, you can bring learn and iq.wiki up a little bit more. and leave in some space below. on figma there is like 56px spacing image
> 
> the distance here is much. A few px more to bridge the gap image

@Simplypheyie96, this is not part of the issue...But I will fix it now though.

**Comment by Simplypheyie96** [comment]
@Emmanueldmlr i don't know. anything to make them not appear on the dashboard. either deleting or hiding

**Comment by Simplypheyie96** [comment]
> > Perhaps, you can bring learn and iq.wiki up a little bit more. and leave in some space below. on figma there is like 56px spacing image
> > the distance here is much. A few px more to bridge the gap image
> 
> @Simplypheyie96, this is not part of the issue...But I will fix it now though.

i thought that removing settings and the brainies might have affected that, so it is somewhat related. Right?

**Comment by Emmanueldmlr** [comment]
> > > Perhaps, you can bring learn and iq.wiki up a little bit more. and leave in some space below. on figma there is like 56px spacing image
> > > the distance here is much. A few px more to bridge the gap image
> > 
> > 
> > @Simplypheyie96, this is not part of the issue...But I will fix it now though.
> 
> i thought that removing settings and the brainies might have affected that, so it is somewhat related. Right?

no...not related...But don't worry, I will handle it now.

**Comment by Emmanueldmlr** [comment]
@Simplypheyie96...all set now?

**Comment by Emmanueldmlr** [comment]
@Simplypheyie96, if there are any other fixes that are critical for launch, you can assign them to me

**Pull request merged**
